---
theme: alembic-jekyll-theme
exclude:
- vendor/bundle
- README.md
- Gemfile
- Gemfile.lock
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
url: https://now.ronbronson.com
baseurl: ''
title: Ron Bronson
description: Digital transformation, et. al.
permalink: pretty
logo: 
paginate: "5"
paginate_path: blog/page:num
navigation_header:
- title: Home
  url: "/"
- title: Talks
  url: "/about/"
- title: Blog
  url: "/blog/"
navigation_footer:
- title: Back to top
  url: "#top"
collections:
  posts:
    title: Blog
    output: true
    description: A blog for Ron Bronson, but don't get your hopes up.
    feature_text: 'Blog

'
    feature_image: https://imgur.com/a/KKi8qKv
