---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: ''
  label: Pages
  create: all
  match: "*.md"
  exclude: "{README.md}"
  templates:
  - page
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - post
- type: heading
  label: Config
- type: document
  path: _config.yml
  label: Jekyll
- type: document
  path: netlify.toml
  label: Netlify
upload_dir: uploads
public_path: "/media"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
